### ISSUE TITLE
[Feature Suggestion] Recurring rewards

### ISSUE THREAD

**Issue by tooobiiii** [GRX005/Velocity-PlayTime#18]
### What do we mean by that?

Instead of having to create multiple reward milestones for the same usage, you could implement recurring rewards which basically execute a command / action (example below) for every x time played. In addition to that, increments for that specific x time value could be made so that it gets harder to achieve over time while working to an optional certain maximum value or infinite incrementation.

### Why this would be a good feature

It makes configuring a lot easier when implementing similar features so that you dont have to hardcode every single milestone in a long long config.yml. In my opinion, many servers use features to showcase players "progress" while still making it hard to achieve.

### Example use-case

For our usage specifically, we would use this to have crate keys given every (at the start) 30m. Which then increments slowly until reaching a max value (3h). 
This would make up more flexibility when using your playtime plugin as well as various feature expansions.

### How it may look in the configuration

```yml
Recurring_Rewards: 
  <identifier>:
    start_value: 1800000 # half an hour
    increment: 1% or time value idc
    max_value: 10800000 # 3 hours
    command: <command>
```

Optionally for easier but limited implementation you could just add an option to repeat the last reward instead of doing nothing.
